# Generated by Django 2.2.2 on 2019-06-08 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('category', models.CharField(choices=[('winter', 'Winter'), ('autumn', 'Autumn'), ('spring', 'Spring'), ('summer', 'Summer'), ('common', 'Common'), ('family', 'Family'), ('nature', 'Nature'), ('girl', 'Girl'), ('joy', 'Joy'), ('animals', 'Animals')], default='common', max_length=20)),
                ('date', models.DateTimeField(db_index=True, verbose_name='Date and Time')),
                ('price', models.FloatField(verbose_name='Price')),
                ('like', models.IntegerField(db_index=True, default=0, verbose_name='Like')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Surname')),
                ('login', models.CharField(max_length=30, verbose_name='Login')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_image.Image', verbose_name='purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('id_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_image.Image', verbose_name='purchase')),
            ],
        ),
    ]
